// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_3 = "CgkIqPap-MAGEAIQEA"; // <GPGSID>
        public const string achievement_4 = "CgkIqPap-MAGEAIQEQ"; // <GPGSID>
        public const string achievement_5 = "CgkIqPap-MAGEAIQEw"; // <GPGSID>
        public const string achievement_gamer = "CgkIqPap-MAGEAIQEg"; // <GPGSID>
        public const string achievement_welcome = "CgkIqPap-MAGEAIQDA"; // <GPGSID>
        public const string achievement_pathetic = "CgkIqPap-MAGEAIQFQ"; // <GPGSID>
        public const string achievement_magnetize = "CgkIqPap-MAGEAIQCw"; // <GPGSID>
        public const string achievement_a_win_against_time = "CgkIqPap-MAGEAIQDw"; // <GPGSID>
        public const string achievement_loser = "CgkIqPap-MAGEAIQFA"; // <GPGSID>
        public const string achievement_champion_of_the_internet = "CgkIqPap-MAGEAIQFw"; // <GPGSID>
        public const string achievement_winner = "CgkIqPap-MAGEAIQGA"; // <GPGSID>
        public const string achievement_champion = "CgkIqPap-MAGEAIQGQ"; // <GPGSID>
        public const string achievement_winner_of_the_internet = "CgkIqPap-MAGEAIQFg"; // <GPGSID>
        public const string achievement_1 = "CgkIqPap-MAGEAIQDQ"; // <GPGSID>
        public const string achievement_2 = "CgkIqPap-MAGEAIQDg"; // <GPGSID>

}

