// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_unlimited_power = "CgkIqPap-MAGEAIQHg"; // <GPGSID>
        public const string achievement_gamer = "CgkIqPap-MAGEAIQEg"; // <GPGSID>
        public const string achievement_welcome = "CgkIqPap-MAGEAIQDA"; // <GPGSID>
        public const string achievement_pathetic = "CgkIqPap-MAGEAIQFQ"; // <GPGSID>
        public const string achievement_winner_of_the_internet = "CgkIqPap-MAGEAIQFg"; // <GPGSID>
        public const string achievement_a_fine_addition = "CgkIqPap-MAGEAIQHw"; // <GPGSID>
        public const string achievement_loser = "CgkIqPap-MAGEAIQFA"; // <GPGSID>
        public const string achievement_attractive_gameplay = "CgkIqPap-MAGEAIQCw"; // <GPGSID>
        public const string achievement_whole_row = "CgkIqPap-MAGEAIQHA"; // <GPGSID>
        public const string achievement_magnetize = "CgkIqPap-MAGEAIQHQ"; // <GPGSID>
        public const string achievement_champion_of_the_internet = "CgkIqPap-MAGEAIQFw"; // <GPGSID>
        public const string achievement_durable_batteries = "CgkIqPap-MAGEAIQEA"; // <GPGSID>
        public const string achievement_power = "CgkIqPap-MAGEAIQGw"; // <GPGSID>
        public const string achievement_ahead_of_time = "CgkIqPap-MAGEAIQDw"; // <GPGSID>
        public const string achievement_opportunist = "CgkIqPap-MAGEAIQGg"; // <GPGSID>
        public const string leaderboard_credits = "CgkIqPap-MAGEAIQIA"; // <GPGSID>
        public const string achievement_esports_player = "CgkIqPap-MAGEAIQEw"; // <GPGSID>

}

